# Generated by Django 4.0.2 on 2023-04-21 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='food')),
            ],
        ),
        migrations.CreateModel(
            name='FoodShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('openinghour', models.CharField(max_length=5)),
                ('closinghour', models.CharField(max_length=5)),
                ('description', models.TextField()),
                ('ownercontact', models.CharField(max_length=12)),
                ('saleprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=28, max_digits=30)),
                ('long', models.DecimalField(decimal_places=28, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ratingMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.foodshop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasoning', models.CharField(max_length=50)),
                ('temperature', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('Basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.basket')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.dish')),
            ],
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('lat', 'long'), name='coordinate'),
        ),
        migrations.AddField(
            model_name='foodshop',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.dish'),
        ),
        migrations.AddField(
            model_name='foodshop',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.location'),
        ),
        migrations.AddField(
            model_name='comments',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.dish'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user'),
        ),
        migrations.AddField(
            model_name='basket',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.user'),
        ),
        migrations.AddField(
            model_name='addshop',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.foodshop'),
        ),
        migrations.AddField(
            model_name='addshop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user'),
        ),
    ]
