# Generated by Django 4.0.2 on 2023-04-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingmeal',
            name='comment',
        ),
        migrations.AddField(
            model_name='ratingmeal',
            name='point',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=2),
            preserve_default=False,
        ),
    ]
