# Generated by Django 4.0.2 on 2023-04-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_ratingmeal_comment_ratingmeal_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=13),
        ),
    ]
